### ISSUE TITLE
Support for manylinux

### ISSUE THREAD

**Issue by chromano** [carloshatch/wi#1]
Currently, we are relying on the `wheel` module to find whether a .whl can be installed on the destination arch, however that module doesn't provide support for manylinux versions (i.e, it won't recognise packages distributed as such).

**Comment by jayvdb** [comment]
Re-check?  wheel might now support manylinux , but https://github.com/chromano/wi/issues/9 also needs to be fixed.

**Comment by carloshatch** [comment]
@jayvdb Thanks for bringing this up, I will try to update the implementation the coming days, though if you done it already, I would appreciate a PR.

**Comment by carloshatch** [comment]
Closed in favor of #9
