### ISSUE TITLE
Allow to point to a private PyPI repo

### ISSUE THREAD

**Issue by jaimebuelta** [carloshatch/wi#3]
At the moment the repo to pull from is hardcoded to be

```
PACKAGES_REPO_URL = 'https://pypi.python.org/pypi'
```

Allowing to connect to other repos will help a lot, ideally sharing the same argument options as pip (https://pip.pypa.io/en/stable/reference/pip/?highlight=trusted-host#cmdoption-trusted-host, https://pip.pypa.io/en/stable/reference/pip_wheel/#index-url ) for clarity

```
wi --index-url=http://my_own_repo.company.com --trusted-host my_own_repo.company.com
```

The trusted host is to avoid requiring https

**Comment by nicoulaj** [comment]
In the short term `PACKAGES_REPO_URL` could at least be an environment variable.
